# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 196)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(4, 4, 793, 171))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(18, 8, 119, 16))
        self.label_5.setObjectName("label_5")
        self.DbOutputPath = QtWidgets.QLineEdit(self.tab)
        self.DbOutputPath.setGeometry(QtCore.QRect(144, 6, 537, 20))
        self.DbOutputPath.setObjectName("DbOutputPath")
        self.BrowseForDbOutput = QtWidgets.QPushButton(self.tab)
        self.BrowseForDbOutput.setGeometry(QtCore.QRect(696, 6, 83, 23))
        self.BrowseForDbOutput.setObjectName("BrowseForDbOutput")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(504, 120, 81, 16))
        self.label_4.setObjectName("label_4")
        self.ImageTypeCombo = QtWidgets.QComboBox(self.tab)
        self.ImageTypeCombo.setGeometry(QtCore.QRect(602, 118, 81, 22))
        self.ImageTypeCombo.setObjectName("ImageTypeCombo")
        self.ImageTypeCombo.addItem("")
        self.ImageTypeCombo.addItem("")
        self.CreateDbButton = QtWidgets.QPushButton(self.tab)
        self.CreateDbButton.setGeometry(QtCore.QRect(696, 118, 83, 23))
        self.CreateDbButton.setObjectName("CreateDbButton")
        self.ShapeRootEdit = QtWidgets.QLineEdit(self.tab)
        self.ShapeRootEdit.setGeometry(QtCore.QRect(144, 62, 537, 20))
        self.ShapeRootEdit.setObjectName("ShapeRootEdit")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(18, 36, 109, 16))
        self.label_6.setObjectName("label_6")
        self.BrowseForShapeRoot = QtWidgets.QPushButton(self.tab)
        self.BrowseForShapeRoot.setGeometry(QtCore.QRect(696, 62, 83, 23))
        self.BrowseForShapeRoot.setObjectName("BrowseForShapeRoot")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(18, 64, 109, 16))
        self.label_7.setObjectName("label_7")
        self.ImageRootDirEdit = QtWidgets.QLineEdit(self.tab)
        self.ImageRootDirEdit.setGeometry(QtCore.QRect(144, 34, 537, 20))
        self.ImageRootDirEdit.setObjectName("ImageRootDirEdit")
        self.BrowseForImageRoot = QtWidgets.QPushButton(self.tab)
        self.BrowseForImageRoot.setGeometry(QtCore.QRect(696, 34, 83, 23))
        self.BrowseForImageRoot.setObjectName("BrowseForImageRoot")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(18, 54, 109, 16))
        self.label_3.setObjectName("label_3")
        self.OutputDirectoryEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OutputDirectoryEdit.setGeometry(QtCore.QRect(118, 52, 577, 20))
        self.OutputDirectoryEdit.setObjectName("OutputDirectoryEdit")
        self.BrowseForImageDir = QtWidgets.QPushButton(self.tab_2)
        self.BrowseForImageDir.setGeometry(QtCore.QRect(706, 20, 75, 23))
        self.BrowseForImageDir.setObjectName("BrowseForImageDir")
        self.BrowseForDb = QtWidgets.QPushButton(self.tab_2)
        self.BrowseForDb.setGeometry(QtCore.QRect(706, 84, 75, 23))
        self.BrowseForDb.setObjectName("BrowseForDb")
        self.ClearButton = QtWidgets.QPushButton(self.tab_2)
        self.ClearButton.setGeometry(QtCore.QRect(620, 116, 75, 23))
        self.ClearButton.setObjectName("ClearButton")
        self.OutputDirectoryEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.OutputDirectoryEdit_2.setGeometry(QtCore.QRect(118, 84, 577, 20))
        self.OutputDirectoryEdit_2.setObjectName("OutputDirectoryEdit_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(18, 22, 109, 16))
        self.label.setObjectName("label")
        self.ImageDirInput = QtWidgets.QLineEdit(self.tab_2)
        self.ImageDirInput.setGeometry(QtCore.QRect(118, 20, 577, 20))
        self.ImageDirInput.setObjectName("ImageDirInput")
        self.BrowseForOutputDir = QtWidgets.QPushButton(self.tab_2)
        self.BrowseForOutputDir.setGeometry(QtCore.QRect(706, 52, 75, 23))
        self.BrowseForOutputDir.setObjectName("BrowseForOutputDir")
        self.ProcessButton = QtWidgets.QPushButton(self.tab_2)
        self.ProcessButton.setGeometry(QtCore.QRect(708, 116, 75, 23))
        self.ProcessButton.setObjectName("ProcessButton")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(18, 84, 109, 16))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image & Shape Renamer"))
        self.label_5.setText(_translate("MainWindow", "DB Output Path"))
        self.BrowseForDbOutput.setText(_translate("MainWindow", "Save As"))
        self.label_4.setText(_translate("MainWindow", "Image File Type"))
        self.ImageTypeCombo.setItemText(0, _translate("MainWindow", ".img"))
        self.ImageTypeCombo.setItemText(1, _translate("MainWindow", ".tif"))
        self.CreateDbButton.setText(_translate("MainWindow", "Build Database"))
        self.label_6.setText(_translate("MainWindow", "Image Root Directory"))
        self.BrowseForShapeRoot.setText(_translate("MainWindow", "Browse"))
        self.label_7.setText(_translate("MainWindow", "Shape Root Directory"))
        self.BrowseForImageRoot.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Build DB"))
        self.label_3.setText(_translate("MainWindow", "Output Directory"))
        self.BrowseForImageDir.setText(_translate("MainWindow", "Browse"))
        self.BrowseForDb.setText(_translate("MainWindow", "Browse"))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.label.setText(_translate("MainWindow", "Image Directory:"))
        self.BrowseForOutputDir.setText(_translate("MainWindow", "Browse"))
        self.ProcessButton.setText(_translate("MainWindow", "Process"))
        self.label_8.setText(_translate("MainWindow", "DB File:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Move Images && Shapes"))

